### ISSUE TITLE
큰일났음 동일 오류인데 브라우저마다 메시지가 다름

### ISSUE THREAD

**Issue by haks1999** [baeum/hakstrace#19]
firefox - unterminated string literal  
safari - Unexpected EOF 
chrome - Uncaught SyntaxError: Unexpected token ILLEGAL
IE8 (kr) - 종결되지 않은 문자열 상수입니다.  

메시지 가지고 동일 오류 여부 확인할려고 했는데;;; 
column, row 번호로 동일 오류라고 하기엔 구문 오류는 다 0,-1 이라서 안 되요.
메시지랑 url 로 동일 오류로 합치면 
오류 당 브라우저는 하나만 나올듯요

**Comment by gunlee01** [comment]
다른 브라우저면 걍 다른 오류......로 편하게 생각하기.

**Comment by gunlee01** [comment]
Hey Haks!

HaksTrace 이름 뭘로 하지???? 이건 차차 생각하고

주요 화면들 캡쳐 회신 부탁
이쁘게.
창크기는 1024 미만으로 다가....
아니면... 클라우드라면
접속할 수 있는 IP를 알려다오. 내가 뜰테니... 

ㅋㅋㅋ

**Comment by haks1999** [comment]
![image](https://cloud.githubusercontent.com/assets/6283501/7692722/3f649a8a-fe02-11e4-822f-b934b29cdf44.png)
![image](https://cloud.githubusercontent.com/assets/6283501/7692736/582dddc4-fe02-11e4-8c30-817a4a5fec7c.png)
![image](https://cloud.githubusercontent.com/assets/6283501/7692741/6c6e07be-fe02-11e4-8cee-5f7ed6e20ff9.png)
![image](https://cloud.githubusercontent.com/assets/6283501/7692749/7f04c2dc-fe02-11e4-81b6-a252bebb6f52.png)
